// Re-export all functions from the database module
// This maintains backwards compatibility with existing API routes
export {
  getMasters,
  getMasterById,
  addMaster,
  updateMaster,
  deleteMaster,
  getServicesForMaster,
  getServices,
  getServicesForMasters,
  addServiceToMaster,
  deleteService,
  getSlotSettings,
  upsertSlotSettings,
  applySlotSettingsToFutureDates,
  generateSlotsForDay,
  getSlotsForDay,
  getAdminSlotsForDay,
  bookSlot,
  getUserBookings,
  cancelBooking,
  getBookingById,
  getAllBookings,
  adminCancelBooking,
  toggleSlotDisabled,
  cleanupPastBookings,
} from './database'
